ALTER TABLE "GameConfig"
  ADD COLUMN IF NOT EXISTS "maxPlaysPerDay" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "withdrawMinPlays" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "withdrawCooldownMs" INTEGER NOT NULL DEFAULT 60000,
  ADD COLUMN IF NOT EXISTS "withdrawRiskThreshold" INTEGER NOT NULL DEFAULT 70,
  ADD COLUMN IF NOT EXISTS "maxReferralsPerIpPerDay" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "waitlistRiskThreshold" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS "rapidOnboardingWindowMs" INTEGER NOT NULL DEFAULT 10000,
  ADD COLUMN IF NOT EXISTS "minPlayIntervalMs" INTEGER NOT NULL DEFAULT 300,
  ADD COLUMN IF NOT EXISTS "referralWindowMs" INTEGER NOT NULL DEFAULT 86400000;
