ALTER TABLE "GameConfig"
  ADD COLUMN IF NOT EXISTS "maxPayoutMultiplier" DECIMAL(10,4) NOT NULL DEFAULT 1.2,
  ADD COLUMN IF NOT EXISTS "minRtpModifier" DECIMAL(10,4) NOT NULL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS "maxRtpModifier" DECIMAL(10,4) NOT NULL DEFAULT 1.2;